FROM node:16-alpine
WORKDIR '/app'
COPY package.json yarn.lock ./
COPY packages/gateway-service/package.json /app/packages/gateway-service/package.json
COPY packages/auth-service/package.json /app/packages/auth-service/package.json
COPY lerna.json /app/lerna.json
RUN yarn
COPY . .
RUN yarn build:gateway

CMD ["yarn","run","start:prod:gateway"]
