FROM node:16-alpine
WORKDIR '/app/kanban'
COPY package.json yarn.lock ./
COPY packages/kanban-service/package.json /app/kanban/packages/kanban-service/package.json
COPY lerna.json /app/kanban/lerna.json
RUN yarn
COPY . .
RUN yarn build:kanban

CMD ["yarn","run","start:prod:kanban"]
